apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dovecot
  namespace: monitoring
  labels:
    prometheus: monitoring
spec:
  jobLabel: dovecot
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: dovecot
  endpoints:
    - port: metrics
